In [15]:
import tensorflow as tf
import tensorflow.data as d
import tensorflow.keras.layers as n
ds = d.Dataset.range(10)
for val in ds:
    print(val.numpy())

0
1
2
3
4
5
6
7
8
9


In [16]:
ds_0=ds.window(5, shift=1)
for window_ds in ds_0:
    for val in window_ds:
        print(val.numpy(), end=" ")
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [17]:
ds_1=ds.window(5, shift=1, drop_remainder=True)
for window_ds in ds_1:
    for val in window_ds:
        print(val.numpy(), end=" ")
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [18]:
ds_2=ds_1.flat_map(lambda window: window.batch(5))
#Single tensor units for dataset
for window in ds_2:
    print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [19]:
ds_3 = ds_2.map(lambda window: (window[:-1], window[-1:]))
for x,y in ds_3: print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [20]:
ds_4=ds_3.shuffle(buffer_size=10)
for x,y in ds_4: print(x.numpy(), y.numpy())

[1 2 3 4] [5]
[4 5 6 7] [8]
[2 3 4 5] [6]
[5 6 7 8] [9]
[3 4 5 6] [7]
[0 1 2 3] [4]


In [26]:
ds_5 = ds_4.batch(2).prefetch(1)
for x,y in ds_5:
    print("x: {}".format(x.numpy()))
    print("y: {}".format(y.numpy()))

x: [[5 6 7 8]
 [3 4 5 6]]
y: [[9]
 [7]]
x: [[4 5 6 7]
 [1 2 3 4]]
y: [[8]
 [5]]
x: [[0 1 2 3]
 [2 3 4 5]]
y: [[4]
 [6]]
